//! GPU kernel launcher for clause-parallel gradient SAT.
//!
//! Manages device memory and kernel dispatch for the Axis 1 loss kernel.
//! The PTX is compiled at build time by `warp-types-builder` and embedded
//! via `include!()`.
//!
//! # Usage
//!
//! ```ignore
//! let ctx = GpuContext::new()?;
//! let loss = ctx.total_loss(&soa, &x)?;
//! ```

use crate::gpu_gradient::ClauseDataSoA;
use cudarc::driver::*;
use std::sync::Arc;

// Generated by WarpBuilder in build.rs — contains KERNEL_PTX and Kernels struct.
mod sat_gpu_kernels {
    include!(concat!(env!("OUT_DIR"), "/kernels.rs"));
}

const WARP_SIZE: u32 = 32;

/// GPU context holding CUDA device, stream, and loaded kernels.
///
/// Created once, reused across gradient iterations. Device buffers for
/// clause data are uploaded once (they don't change during optimization);
/// variable values are re-uploaded each iteration.
pub struct GpuContext {
    stream: Arc<CudaStream>,
    kernels: sat_gpu_kernels::Kernels,
}

/// Device-side SoA clause data. Uploaded once, reused across iterations.
pub struct GpuClauseData {
    vars0: CudaSlice<u32>,
    vars1: CudaSlice<u32>,
    vars2: CudaSlice<u32>,
    negs0: CudaSlice<u32>,
    negs1: CudaSlice<u32>,
    negs2: CudaSlice<u32>,
    weights: CudaSlice<f64>,
    /// Output buffer for per-batch partial sums.
    output: CudaSlice<f64>,
    num_clauses: u32,
    num_batches: u32,
}

/// Errors from GPU operations.
#[derive(Debug)]
pub enum GpuError {
    Cuda(String),
}

impl std::fmt::Display for GpuError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GpuError::Cuda(s) => write!(f, "CUDA error: {}", s),
        }
    }
}

impl std::error::Error for GpuError {}

impl From<cudarc::driver::DriverError> for GpuError {
    fn from(e: cudarc::driver::DriverError) -> Self {
        GpuError::Cuda(e.to_string())
    }
}

impl GpuContext {
    /// Initialize CUDA and load the SAT kernels.
    pub fn new() -> Result<Self, GpuError> {
        let ctx = CudaContext::new(0)?;
        let stream = ctx.default_stream();
        let kernels =
            sat_gpu_kernels::Kernels::load(&ctx).map_err(|e| GpuError::Cuda(e.to_string()))?;
        Ok(GpuContext { stream, kernels })
    }

    /// Upload SoA clause data to the GPU. Do this once per problem instance.
    pub fn upload_clause_data(&self, soa: &ClauseDataSoA) -> Result<GpuClauseData, GpuError> {
        let s = &self.stream;

        // Convert bool negation flags to u32 (0 or 1) for GPU
        let negs0_u32: Vec<u32> = soa.negs[0].iter().map(|&b| b as u32).collect();
        let negs1_u32: Vec<u32> = soa.negs[1].iter().map(|&b| b as u32).collect();
        let negs2_u32: Vec<u32> = soa.negs[2].iter().map(|&b| b as u32).collect();

        let num_batches = soa.num_batches() as u32;

        Ok(GpuClauseData {
            vars0: s.clone_htod(&soa.vars[0])?,
            vars1: s.clone_htod(&soa.vars[1])?,
            vars2: s.clone_htod(&soa.vars[2])?,
            negs0: s.clone_htod(&negs0_u32)?,
            negs1: s.clone_htod(&negs1_u32)?,
            negs2: s.clone_htod(&negs2_u32)?,
            weights: s.clone_htod(&soa.weights)?,
            output: s.clone_htod(&vec![0.0f64; num_batches as usize])?,
            num_clauses: soa.num_clauses as u32,
            num_batches,
        })
    }

    /// Re-upload weights after clause weight update (EMA adaptation).
    pub fn update_weights(
        &self,
        gpu_data: &mut GpuClauseData,
        soa: &ClauseDataSoA,
    ) -> Result<(), GpuError> {
        gpu_data.weights = self.stream.clone_htod(&soa.weights)?;
        Ok(())
    }

    /// Compute total loss on GPU. Call each gradient iteration.
    ///
    /// Uploads variable values, launches kernel, downloads + sums partial results.
    /// The kernel result is identical to `total_loss_simwarp()` — same butterfly
    /// reduce, same operation order, same floating-point result.
    pub fn total_loss(&self, gpu_data: &GpuClauseData, x: &[f64]) -> Result<f64, GpuError> {
        let s = &self.stream;

        // Upload current variable values (changes each iteration)
        let dev_x = s.clone_htod(x)?;

        // Launch: one block per warp-batch, 32 threads per block
        unsafe {
            s.launch_builder(&self.kernels.clause_loss_reduce)
                .arg(&gpu_data.vars0)
                .arg(&gpu_data.vars1)
                .arg(&gpu_data.vars2)
                .arg(&gpu_data.negs0)
                .arg(&gpu_data.negs1)
                .arg(&gpu_data.negs2)
                .arg(&gpu_data.weights)
                .arg(&dev_x)
                .arg(&gpu_data.output)
                .arg(&gpu_data.num_clauses)
                .launch(LaunchConfig {
                    grid_dim: (gpu_data.num_batches, 1, 1),
                    block_dim: (WARP_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                })?;
        }

        // Download partial sums and accumulate on CPU
        let partial_sums = s.clone_dtoh(&gpu_data.output)?;
        Ok(partial_sums.iter().sum())
    }

    /// Fused loss + gradient on GPU. Single kernel launch.
    ///
    /// Returns `(total_loss, gradient_vec)`. The gradient is accumulated via
    /// f64 atomicAdd — non-deterministic reduction order means results match
    /// CPU to ~1e-10 but are not bit-identical.
    pub fn total_loss_and_grad(
        &self,
        gpu_data: &GpuClauseData,
        x: &[f64],
        num_vars: usize,
    ) -> Result<(f64, Vec<f64>), GpuError> {
        let s = &self.stream;

        let dev_x = s.clone_htod(x)?;
        // Zero-initialized gradient accumulator
        let dev_grad = s.clone_htod(&vec![0.0f64; num_vars])?;

        unsafe {
            s.launch_builder(&self.kernels.clause_loss_grad_fused)
                .arg(&gpu_data.vars0)
                .arg(&gpu_data.vars1)
                .arg(&gpu_data.vars2)
                .arg(&gpu_data.negs0)
                .arg(&gpu_data.negs1)
                .arg(&gpu_data.negs2)
                .arg(&gpu_data.weights)
                .arg(&dev_x)
                .arg(&gpu_data.output)
                .arg(&dev_grad)
                .arg(&gpu_data.num_clauses)
                .launch(LaunchConfig {
                    grid_dim: (gpu_data.num_batches, 1, 1),
                    block_dim: (WARP_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                })?;
        }

        let partial_sums = s.clone_dtoh(&gpu_data.output)?;
        let grad = s.clone_dtoh(&dev_grad)?;
        Ok((partial_sums.iter().sum(), grad))
    }

    /// GPU device name (for diagnostics).
    pub fn device_name(&self) -> String {
        "GPU".to_string()
    }

    // ── Device-resident iteration state ─────────────────────────────────

    /// Allocate device-resident buffers for the gradient iteration loop.
    ///
    /// Keeps x, grad, and velocity on device across iterations, eliminating
    /// the per-iteration host↔device transfer of grad (download) and x (upload).
    pub fn alloc_iter_state(&self, x: &[f64]) -> Result<GpuIterState, GpuError> {
        let s = &self.stream;
        let num_vars = x.len();
        let num_var_batches = ((num_vars + WARP_SIZE as usize - 1) / WARP_SIZE as usize) as u32;

        Ok(GpuIterState {
            dev_x: s.clone_htod(x)?,
            dev_grad: s.clone_htod(&vec![0.0f64; num_vars])?,
            dev_velocity: s.clone_htod(&vec![0.0f64; num_vars])?,
            grad_norm_output: s.clone_htod(&vec![0.0f64; num_var_batches as usize])?,
            dev_lr: s.clone_htod(&[0.0f64])?,
            dev_momentum: s.clone_htod(&[0.0f64])?,
            num_vars: num_vars as u32,
            num_var_batches,
        })
    }

    /// Run one gradient iteration on GPU: fused loss+grad → variable update → grad norm.
    ///
    /// Returns (total_loss, grad_norm_sq). All intermediate data stays on device.
    /// The only downloads are: loss partial sums (num_batches × 8 bytes) and
    /// grad norm partial sums (num_var_batches × 8 bytes).
    pub fn gpu_iteration(
        &self,
        gpu_data: &GpuClauseData,
        state: &mut GpuIterState,
        lr: f64,
        momentum: f64,
    ) -> Result<(f64, f64), GpuError> {
        let s = &self.stream;

        // Zero grad accumulator for this iteration
        let zeros = vec![0.0f64; state.num_vars as usize];
        state.dev_grad = s.clone_htod(&zeros)?;

        // Upload scalar parameters
        state.dev_lr = s.clone_htod(&[lr])?;
        state.dev_momentum = s.clone_htod(&[momentum])?;

        // ── Kernel 1: fused loss + gradient ──
        unsafe {
            s.launch_builder(&self.kernels.clause_loss_grad_fused)
                .arg(&gpu_data.vars0)
                .arg(&gpu_data.vars1)
                .arg(&gpu_data.vars2)
                .arg(&gpu_data.negs0)
                .arg(&gpu_data.negs1)
                .arg(&gpu_data.negs2)
                .arg(&gpu_data.weights)
                .arg(&state.dev_x)
                .arg(&gpu_data.output)
                .arg(&state.dev_grad)
                .arg(&gpu_data.num_clauses)
                .launch(LaunchConfig {
                    grid_dim: (gpu_data.num_batches, 1, 1),
                    block_dim: (WARP_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                })?;
        }

        // ── Kernel 2: variable update (reads grad, updates x + velocity) ──
        unsafe {
            s.launch_builder(&self.kernels.variable_update)
                .arg(&state.dev_x)
                .arg(&state.dev_grad)
                .arg(&state.dev_velocity)
                .arg(&state.dev_lr)
                .arg(&state.dev_momentum)
                .arg(&state.num_vars)
                .launch(LaunchConfig {
                    grid_dim: (state.num_var_batches, 1, 1),
                    block_dim: (WARP_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                })?;
        }

        // ── Kernel 3: gradient norm reduction (reads grad, reduces grad²) ──
        unsafe {
            s.launch_builder(&self.kernels.grad_norm_reduce)
                .arg(&state.dev_grad)
                .arg(&state.grad_norm_output)
                .arg(&state.num_vars)
                .launch(LaunchConfig {
                    grid_dim: (state.num_var_batches, 1, 1),
                    block_dim: (WARP_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                })?;
        }

        // Download only the small aggregation buffers
        let loss_partials = s.clone_dtoh(&gpu_data.output)?;
        let norm_partials = s.clone_dtoh(&state.grad_norm_output)?;

        let total_loss: f64 = loss_partials.iter().sum();
        let grad_norm_sq: f64 = norm_partials.iter().sum();

        Ok((total_loss, grad_norm_sq))
    }

    /// Download current x values from device for verification.
    pub fn download_x(&self, state: &GpuIterState) -> Result<Vec<f64>, GpuError> {
        Ok(self.stream.clone_dtoh(&state.dev_x)?)
    }

    /// Re-upload x values to device (e.g., after host-side random init for a new start).
    pub fn upload_x(&self, state: &mut GpuIterState, x: &[f64]) -> Result<(), GpuError> {
        state.dev_x = self.stream.clone_htod(x)?;
        state.dev_velocity = self.stream.clone_htod(&vec![0.0f64; x.len()])?;
        Ok(())
    }
}

/// Device-resident state for the gradient iteration loop.
///
/// Holds x, grad, and velocity on GPU across iterations. Created once per
/// solve attempt, re-uploaded per start (random init).
pub struct GpuIterState {
    dev_x: CudaSlice<f64>,
    dev_grad: CudaSlice<f64>,
    dev_velocity: CudaSlice<f64>,
    grad_norm_output: CudaSlice<f64>,
    dev_lr: CudaSlice<f64>,
    dev_momentum: CudaSlice<f64>,
    num_vars: u32,
    num_var_batches: u32,
}
